# Generated by Django 5.1.1 on 2024-09-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_cartitem_order_orderitem_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tran_id',
            field=models.CharField(default='ok', max_length=50),
        ),
    ]
